---
# APT cache TTL in seconds.
apt_cache_valid_time: 3600

# Whether to enable a package repository for Docker.
enable_docker_repo: "{% if ansible_facts.distribution == 'openEuler' %}false{% else %}true{% endif %}"

# Docker APT repository configuration.
docker_apt_url: "https://download.docker.com/linux/{{ ansible_facts.distribution | lower }}"
docker_apt_repo: "deb [signed-by=/etc/apt/keyrings/docker.asc] {{ docker_apt_url }} {{ ansible_facts.distribution_release }} stable"
docker_apt_key_file: "gpg"
docker_apt_package: "docker-ce"
docker_apt_package_pin: ""

# Docker Yum repository configuration.
docker_yum_url: "https://download.docker.com/linux/centos"
docker_yum_baseurl: "{{ docker_yum_url }}/$releasever/$basearch/stable"
docker_yum_gpgkey: "{{ docker_yum_url }}/gpg"
docker_yum_gpgcheck: true
docker_yum_package: "{% if ansible_facts.distribution == 'openEuler' %}docker{{ '-' + docker_yum_package_pin if (docker_yum_package_pin | length > 0) else '' }}{% else %}docker-ce{{ '-' + docker_yum_package_pin if (docker_yum_package_pin | length > 0) else '' }}{% endif %}"
docker_yum_package_pin: ""

# List of packages to install.
docker_packages:
  - "{{ docker_apt_package if ansible_facts.os_family == 'Debian' else docker_yum_package }}"
  - "{% if ansible_facts.os_family == 'Debian' %}apparmor{% endif %}"
  - "{% if not docker_disable_default_iptables_rules | bool %}iptables{% endif %}"

docker_storage_driver: ""
docker_custom_config: "{% if ansible_facts.distribution == 'openEuler' %}{\"exec-opts\": [\"native.umask=normal\"]}{% else %}{}{% endif %}"

docker_http_proxy: ""
docker_https_proxy: ""
docker_no_proxy: ""

docker_log_max_file: "5"
docker_log_max_size: "50m"

# Docker networking options
docker_disable_default_iptables_rules: "yes"
docker_disable_default_network: "{{ docker_disable_default_iptables_rules }}"
docker_disable_ip_forward: "{{ docker_disable_default_iptables_rules }}"

docker_runtime_directory: ""

# NOTE(mnasiadka): Lower 1073741816 nofile limit on EL9 (RHEL9/CentOS Stream 9/Rocky Linux 9)
docker_ulimit_nofile: "{{ ansible_facts.os_family == 'RedHat' and ansible_facts.distribution_major_version == '9' }}"
docker_ulimit_nofile_hard: 1048576
docker_ulimit_nofile_soft: 1048576

# URL of docker registry
docker_registry:
docker_registry_insecure: false

# Path to a CA file for Docker registry
docker_registry_ca:

# Whether to configure Docker and containerd for Zun.
docker_configure_for_zun: false
containerd_configure_for_zun: "{{ docker_configure_for_zun | bool }}"

# Whether to restart docker systemd unit or reload
docker_systemd_reload: false

# Whether to enable auto generate and overwrite docker config
enable_docker_config: true